[build]
  publish = "."

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/gates"
  to = "/gates.html"
  status = 200

[[redirects]]
  from = "/story"
  to = "/story.html"
  status = 200

[[redirects]]
  from = "/retreats"
  to = "/retreats.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

[[redirects]]
  from = "/connect"
  to = "/connect.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
